---
- name: Playbook with Precheck Role
  hosts: localhost

  tasks:
  - name: Precheck block
    block:
      - name: Import the precheck role
        import_role:
          name: precheck
    rescue:
      - fail:
          msg: "PRECHECK FAILED! No need to rollback. Exiting."
 
